{"name": "用户列表查询", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.", "trace": "fixturefunc = <function step_search_users at 0x0000029FFC246C10>, request = <FixtureRequest for <Function test_用户列表查询>>\nkwargs = {'page': <Page url='https://192.168.150.227:31000/sub-app-unity/group'>, 'query_conditions': '  {\\n    \"账号\": \"xixi\",\\n    \"姓名\": \"测试\",\\n    \"职位\": \"普通职员\"\\n  }'}\n\n    def call_fixture_func(\n        fixturefunc: \"_FixtureFunc[FixtureValue]\", request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if is_generator(fixturefunc):\n            fixturefunc = cast(\n                Callable[..., Generator[FixtureValue, None, None]], fixturefunc\n            )\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n\nG:\\softwares\\Python38\\lib\\site-packages\\_pytest\\fixtures.py:908: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntest_cases\\step_defs\\bms\\test_02_user_group.py:62: in step_search_users\n    UserGroupPage(page).search_users(json.loads(query_conditions))\npages\\bms\\user_group_page.py:46: in search_users\n    ExceptionHandle().handle_exception(e)\npages\\bms\\user_group_page.py:42: in search_users\n    self.para_config(para, cond_type_dict[para], para_value)\nutils\\ui_utils\\base_page.py:146: in para_config\n    ExceptionHandle().handle_exception(e)\nutils\\ui_utils\\base_page.py:128: in para_config\n    self.dropdown_locator_by_para(para_value, para, location)\nutils\\ui_utils\\base_page.py:355: in dropdown_locator_by_para\n    ExceptionHandle().handle_exception(e)\nutils\\ui_utils\\base_page.py:353: in dropdown_locator_by_para\n    self.dropdown_check_value(select_value)\nutils\\ui_utils\\base_page.py:399: in dropdown_check_value\n    ExceptionHandle().handle_exception(e)\nutils\\ui_utils\\base_page.py:397: in dropdown_check_value\n    dropdown_locator.locator('//span[text()=\"' + i + '\"]').click()\nvenv\\lib\\site-packages\\playwright\\sync_api\\_generated.py:14764: in click\n    self._sync(\nvenv\\lib\\site-packages\\playwright\\_impl\\_locator.py:153: in click\n    return await self._frame.click(self._selector, strict=True, **params)\nvenv\\lib\\site-packages\\playwright\\_impl\\_frame.py:488: in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\nvenv\\lib\\site-packages\\playwright\\_impl\\_connection.py:59: in send\n    return await self._connection.wrap_api_call(\nvenv\\lib\\site-packages\\playwright\\_impl\\_connection.py:509: in wrap_api_call\n    return await cb()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Channel object at 0x0000029FFC6FE910>, method = 'click', params = {'selector': '.el-select-dropdown.el-popper >> nth=2 >> //span[text()=\"普通职员\"]', 'strict': True}, return_as_dict = False\n\n    async def inner_send(\n        self, method: str, params: Optional[Dict], return_as_dict: bool\n    ) -> Any:\n        if params is None:\n            params = {}\n        if self._connection._error:\n            error = self._connection._error\n            self._connection._error = None\n            raise error\n        callback = self._connection._send_message_to_server(\n            self._object, method, _filter_none(params)\n        )\n        done, _ = await asyncio.wait(\n            {\n                self._connection._transport.on_error_future,\n                callback.future,\n            },\n            return_when=asyncio.FIRST_COMPLETED,\n        )\n        if not callback.future.done():\n            callback.future.cancel()\n>       result = next(iter(done)).result()\nE       playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.\n\nvenv\\lib\\site-packages\\playwright\\_impl\\_connection.py:97: TimeoutError"}, "description": "E:\\Wondersoft_WebUITest\\test_cases\\features\\bms\\user_group.feature: 用户列表查询", "steps": [{"name": "打开网站：'https://192.168.150.227:31000/'", "status": "passed", "parameters": [{"name": "url", "value": "'https://192.168.150.227:31000/'"}], "start": 1718084872031, "stop": 1718084873119}, {"name": "判断是否需要重新登录", "status": "passed", "parameters": [{"name": "full_url", "value": "'https://192.168.150.227:31000/portal-login'"}, {"name": "username", "value": "'admin'"}, {"name": "password", "value": "'Ws-123456'"}], "start": 1718084873124, "stop": 1718084875150}, {"name": "点击一级菜单：'用户管理'", "status": "passed", "parameters": [{"name": "men", "value": "'用户管理'"}], "start": 1718084875152, "stop": 1718084876574}, {"name": "点击二级菜单：'基础数据管理'下的三级菜单：'用户与机构管理'", "status": "passed", "parameters": [{"name": "sec_men", "value": "'基础数据管理'"}, {"name": "thi_men", "value": "'用户与机构管理'"}], "start": 1718084876575, "stop": 1718084876705}, {"name": "根据查询条件查询用户列表，查询条件{'账号': 'xixi', '姓名': '测试', '职位': '普通职员'}", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.\n", "trace": "  File \"G:\\softwares\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"E:\\Wondersoft_WebUITest\\pages\\bms\\user_group_page.py\", line 46, in search_users\n    ExceptionHandle().handle_exception(e)\n  File \"E:\\Wondersoft_WebUITest\\pages\\bms\\user_group_page.py\", line 42, in search_users\n    self.para_config(para, cond_type_dict[para], para_value)\n  File \"E:\\Wondersoft_WebUITest\\utils\\ui_utils\\base_page.py\", line 146, in para_config\n    ExceptionHandle().handle_exception(e)\n  File \"E:\\Wondersoft_WebUITest\\utils\\ui_utils\\base_page.py\", line 128, in para_config\n    self.dropdown_locator_by_para(para_value, para, location)\n  File \"E:\\Wondersoft_WebUITest\\utils\\ui_utils\\base_page.py\", line 355, in dropdown_locator_by_para\n    ExceptionHandle().handle_exception(e)\n  File \"E:\\Wondersoft_WebUITest\\utils\\ui_utils\\base_page.py\", line 353, in dropdown_locator_by_para\n    self.dropdown_check_value(select_value)\n  File \"E:\\Wondersoft_WebUITest\\utils\\ui_utils\\base_page.py\", line 399, in dropdown_check_value\n    ExceptionHandle().handle_exception(e)\n  File \"E:\\Wondersoft_WebUITest\\utils\\ui_utils\\base_page.py\", line 397, in dropdown_check_value\n    dropdown_locator.locator('//span[text()=\"' + i + '\"]').click()\n  File \"E:\\Wondersoft_WebUITest\\venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 14764, in click\n    self._sync(\n  File \"E:\\Wondersoft_WebUITest\\venv\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 113, in _sync\n    return task.result()\n  File \"E:\\Wondersoft_WebUITest\\venv\\lib\\site-packages\\playwright\\_impl\\_locator.py\", line 153, in click\n    return await self._frame.click(self._selector, strict=True, **params)\n  File \"E:\\Wondersoft_WebUITest\\venv\\lib\\site-packages\\playwright\\_impl\\_frame.py\", line 488, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"E:\\Wondersoft_WebUITest\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n  File \"E:\\Wondersoft_WebUITest\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 509, in wrap_api_call\n    return await cb()\n  File \"E:\\Wondersoft_WebUITest\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 97, in inner_send\n    result = next(iter(done)).result()\n"}, "attachments": [{"name": "测试用例运行失败：", "source": "545e1c87-1a1a-4a61-aa57-daf9b7406b17-attachment.attach"}, {"name": "测试用例运行失败：", "source": "c3f9a34e-6b67-4afe-aa0a-a7dbdbf137a8-attachment.attach"}, {"name": "测试用例运行失败：", "source": "078c2c6a-cce6-4f73-a03c-5620d85bea7c-attachment.attach"}, {"name": "测试用例运行失败：", "source": "0d19d7c8-b431-40f2-9258-7a5b8a4c1467-attachment.attach"}], "parameters": [{"name": "query_conditions", "value": "{'账号': 'xixi', '姓名': '测试', '职位': '普通职员'}"}], "start": 1718084876708, "stop": 1718084907536}], "start": 1718084872029, "stop": 1718084907538, "uuid": "f0fdebdf-5285-4159-b337-821f59d1877d", "historyId": "f9976a632641b2640ea95ba055e6fd5b", "testCaseId": "ab3b7279a905963cf6829529ebbc2f19", "fullName": "test_cases.step_defs.bms.test_02_user_group#test_用户列表查询", "labels": [{"name": "feature", "value": "用户及机构管理模块"}, {"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "test_cases.step_defs.bms"}, {"name": "suite", "value": "test_02_user_group"}, {"name": "host", "value": "OFYI7JX9DURTDV6"}, {"name": "thread", "value": "17360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.step_defs.bms.test_02_user_group"}]}